version: '3'
services: 
  jenkins-ans:
     container_name: jenkin_ans
     image: ansjen       
     build:
        context: jenkin_ans
     volumes:
       - "$PWD/jenkins_home:/var/jenkins_home"
     ports:
       - "8080:8080"
     networks:
       - net 
  remote_host:
     container_name: remote_host
     image: remote_host
     build:
       context: Remote_host
     volumes:
       - "$PWD/scripts:/tmp/scripts"
     networks:
       - net 
  dbmain:
     container_name: dbmain
     image: mysql:5.7
#     restart: always
     environment: 
       - "MYSQL_ROOT_PASSWORD=root123"
#    command: --default-authentication-plugin=mysql_native_password
     volumes:
       - "$PWD/databaseBK:/var/lib/mysql"
     networks:
       - net  

  webserver:
     container_name: webserver
     image: webserver
     build: 
       context: webserver
     ports:
       - "88:80" 
     networks:
       - net
  ngios:
    container_name: ngios
    image: jasonrivers/nagios:latest
    ports:
      - "89:80"
    volumes:
      - "$PWD/nagiosETC:/opt/nagios/etc/"
      - "$PWD/nagiosVAR:/opt/nagios/var/"
      - "$PWD/path-to-custom-plugins:/opt/Custom-Nagios-Plugins"
      - "$PWD/path-to-nagiosgraph-var:/opt/nagiosgraph/var"
    networks:
      - net

networks:
    net:      
    


