FROM remote_host

COPY nginx.repo /etc/yum.repos.d/nginx.repo

RUN yum -y install nginx-1.12.2 openssl --enablerepo=nginx && \
    yum -y install https://centos7.iuscommunity.org/ius-release.rpm && \
    yum -y install php71u-fpm php71u-cli php71u-mysqlnd php71u-soap php71u-xml php71u-zip php71u-json php71u-mcrypt php71u-mbstring  php71u-gb --enablerepo=ius && yum clean all 
	
EXPOSE 80 443

VOLUME /var/www/html /var/log/nginx /var/lib/php-fpm /var/log/php-fpm

#RUN setfacl -R -m  u:remote_user:rwx /var/www/html

#COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY start.sh /start.sh
RUN chmod +x /start.sh

CMD /start.sh
